version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: controlacceso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"  # Cambia aquí el puerto de la máquina anfitriona a 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: controlacceso
    depends_on:
      - database

volumes:
  postgres_data:
